---
- name: build abyss cluster node
  hosts: abyss
  tasks:

  - name: upgrade packages
    ansible.builtin.apt:
      name: '*'
      update_cache: yes
      state: latest
    tags: packages

  - name: install wireguard
    apt:
      name: wireguard
      state: latest
    tags: packages

  - name: disable ufw 
    shell: ufw disable && systemctl disable ufw
    args:
      executable: /bin/bash
    tags: ufw
    
  - name: enable and start snapd
    shell: systemctl enable snapd && systemctl start snapd
    args:
      executable: /bin/bash
    tags: snapd
    
  - name: install microk8s snap
    shell:  yes | snap install microk8s --classic 
    args:
      executable: /bin/bash
    tags: snapd
    
  - name: enable community 
    shell: microk8s enable community
    args:
      executable: /bin/bash
    tags: cilium
    
    
...
